abstract: Easy-to-use self-cleaning scratch space.
author: Jonathan Rockway <jrockway@cpan.org
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: Perl
name: Directory-Scratch
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  File::Copy: 0
  File::Path: 0
  File::Slurp: 0
  File::Temp: 0
  Path::Class: 0
tests: t/*/*.t
version: 0.09
